name: Add new resource

on:
  workflow_dispatch:
    inputs:
      category:
        description: "Category (book, blog, tweet, paper, personal)"
        required: true
        type: string
      title:
        description: "Title of the item"
        required: true
        type: string
      url:
        description: "URL of the item"
        required: true
        type: string

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Append to correct JS object
        env:
          TITLE: ${{ github.event.inputs.title }}
          URL: ${{ github.event.inputs.url }}
          CATEGORY: ${{ github.event.inputs.category }}
        run: |
          FILE="index.html"

          case "${CATEGORY,,}" in
            blog) VAR_NAME="blogs" ;;
            tweet) VAR_NAME="Tweet" ;;
            book) VAR_NAME="books" ;;
            paper) VAR_NAME="R_papers" ;;
            personal) VAR_NAME="personalwriteups" ;;
            *) echo "Unknown category: $CATEGORY" && exit 1 ;;
          esac

          # Escape title and URL for JS
          TITLE_ESC=$(printf "%s" "$TITLE" | sed 's/"/\\"/g')
          URL_ESC=$(printf "%s" "$URL" | sed 's/"/\\"/g')
          export VAR_NAME
          export NEW_ENTRY="  \"$TITLE_ESC\": \"$URL_ESC\""

          echo "Appending: $NEW_ENTRY to object $VAR_NAME"

          perl -0777 -i -pe '
            my $var = $ENV{VAR_NAME};
            my $new = $ENV{NEW_ENTRY};
            s/
              (let\s+\Q$var\E\s*=\s*{)      # match start
              (.*?)                         # body
              (\n\s*})                      # end
            /
              my $head = $1;
              my $body = $2;
              my $tail = $3;
              $body =~ s/\\s+\\z//;
              $body = $body ? "$body,\n$new" : "$new";
              "$head$body$tail";
            /sex
          ' "$FILE"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "bot@users.noreply.github.com"
          git add index.html

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Add ${{ github.event.inputs.title }} to ${{ github.event.inputs.category }}"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/astledsa/readings.git
          git push origin main
