name: Add new resource

on:
  workflow_dispatch:
    inputs:
      category:
        description: "Category (book, blog, tweet, paper, personal)"
        required: true
        type: string
      title:
        description: "Title of the item"
        required: true
        type: string
      url:
        description: "URL of the item"
        required: true
        type: string

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Append to correct JS object
        run: |
          CATEGORY=$(echo "${{ github.event.inputs.category }}" | tr '[:upper:]' '[:lower:]')
          FILE="index.html"

          case "$CATEGORY" in
            blog) VAR_NAME="blogs" ;;
            tweet) VAR_NAME="Tweet" ;;
            book) VAR_NAME="books" ;;
            paper) VAR_NAME="R_papers" ;;
            personal) VAR_NAME="personalwriteups" ;;
            *) echo "Unknown category: $CATEGORY" && exit 1 ;;
          esac

          # Escape title and URL safely
          TITLE_ESC=$(printf "%s" "${{ github.event.inputs.title }}" | sed 's/"/\\"/g')
          URL_ESC=$(printf "%s" "${{ github.event.inputs.url }}" | sed 's/"/\\"/g')
          NEW_ENTRY="  \"$TITLE_ESC\": \"$URL_ESC\""

          echo "Appending: $NEW_ENTRY to object $VAR_NAME"

          # Perl-based JS object insertion
          perl -0777 -i -pe "
            s/
              (let\s+$VAR_NAME\s*=\s*{)      # match opening
              (.*?)                          # capture contents
              (\n\s*})                       # match closing
            /
              my \$head = \$1;
              my \$body = \$2;
              my \$tail = \$3;
              my \$new = \"$NEW_ENTRY\";
              \$body =~ s/\s+\z//;
              \$body = \$body ? \"\$body,\\n\$new\" : \"\$new\";
              \"\$head\$body\$tail\";
            /sex
          " \"$FILE\"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "bot@users.noreply.github.com"
          git add index.html

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Add ${{ github.event.inputs.title }} to ${{ github.event.inputs.category }}"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/astledsa/readings.git
          git push origin main
