name: Add new resource

on:
  workflow_dispatch:
    inputs:
      category:
        description: "Category (book, blog, tweet, paper, personal)"
        required: true
        type: string
      title:
        description: "Title of the item"
        required: true
        type: string
      url:
        description: "URL of the item"
        required: true
        type: string

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Append to correct JS object
        env:
          TITLE: ${{ github.event.inputs.title }}
          URL: ${{ github.event.inputs.url }}
          CATEGORY: ${{ github.event.inputs.category }}
        run: |
          FILE="index.html"

          case "${CATEGORY,,}" in
            blog) VAR_NAME="blogs" ;;
            tweet) VAR_NAME="Tweet" ;;
            book) VAR_NAME="books" ;;
            paper) VAR_NAME="R_papers" ;;
            personal) VAR_NAME="personalwriteups" ;;
            *) echo "Unknown category: $CATEGORY" && exit 1 ;;
          esac

          # Escape title and URL
          TITLE_ESC=$(printf "%s" "$TITLE" | sed 's/"/\\"/g')
          URL_ESC=$(printf "%s" "$URL" | sed 's/"/\\"/g')

          echo "Appending: \"$TITLE_ESC\": \"$URL_ESC\" to $VAR_NAME"

          echo '
            use strict;
            use warnings;

            my $var_name = $ENV{"VAR_NAME"};
            my $file = $ENV{"FILE"};
            my $title = $ENV{"TITLE_ESC"};
            my $url = $ENV{"URL_ESC"};

            my $new_line = qq{  "$title": "$url"};

            local $/ = undef;
            open my $fh, "<", $file or die "Cannot read $file: $!";
            my $content = <$fh>;
            close $fh;

            $content =~ s/
              (let\s+\Q$var_name\E\s*=\s*{)      # opening
              (.*?)                              # body
              (\n\s*})                           # closing
            /
              my ($head, $body, $tail) = ($1, $2, $3);
              $body =~ s/\s+\z//;
              $body = $body ? "$body,\n$new_line" : $new_line;
              "$head$body$tail";
            /sex;

            open my $out, ">", $file or die "Cannot write $file: $!";
            print $out $content;
            close $out;
          ' > update.pl

          VAR_NAME=$VAR_NAME FILE=$FILE TITLE_ESC="$TITLE_ESC" URL_ESC="$URL_ESC" perl update.pl

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "bot@users.noreply.github.com"
          git add index.html

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Add ${{ github.event.inputs.title }} to ${{ github.event.inputs.category }}"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/astledsa/readings.git
          git push origin main
