# .github/workflows/add-resource.yml
name: Add new resource

on:
  workflow_dispatch:
    inputs:
      category:
        description: "Category of the resource"
        required: true
        type: choice
        options:
          - book
          - blog
          - tweet
          - paper
          - personal
      title:
        description: "Title of the resource"
        required: true
        type: string
      url:
        description: "URL of the resource"
        required: true
        type: string

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update data file
        env:
          TITLE: ${{ github.event.inputs.title }}
          URL: ${{ github.event.inputs.url }}
          CATEGORY: ${{ github.event.inputs.category }}
        run: |
          # 1. Define the target file and map category to a placeholder marker
          FILE="index.html"
          case "$CATEGORY" in
            blog)     MARKER="// APPEND_BLOGS_HERE" ;;
            tweet)    MARKER="// APPEND_TWEETS_HERE" ;;
            book)     MARKER="// APPEND_BOOKS_HERE" ;;
            paper)    MARKER="// APPEND_PAPERS_HERE" ;;
            personal) MARKER="// APPEND_PERSONAL_HERE" ;;
            *)        echo "Error: Unknown category '$CATEGORY'" && exit 1 ;;
          esac
          
          echo "Category: $CATEGORY"
          echo "Marker: $MARKER"

          # 2. Escape quotes in title and URL for safe insertion
          TITLE_ESC=$(echo "$TITLE" | sed 's/"/\\"/g')
          URL_ESC=$(echo "$URL" | sed 's/"/\\"/g')

          # 3. Prepare the new line to be inserted, WITH a trailing comma.
          # The indentation (4 spaces) is included for nice formatting.
          NEW_LINE="    \"${TITLE_ESC}\": \"${URL_ESC}\","

          # 4. Use sed to find the marker and insert the new line AFTER it.
          # This robustly handles the comma issue for both empty and non-empty objects.
          # The `|` is used as a delimiter to avoid conflicts with slashes.
          sed -i "s|${MARKER}|${MARKER}\n${NEW_LINE}|" "$FILE"

          echo "Successfully appended '$TITLE' to the '$CATEGORY' section in $FILE."

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Note: Fixed a typo here from your original post (`${A{...` -> `${{...`)
          commit_message: "feat(${{ github.event.inputs.category }}): Add '${{ github.event.inputs.title }}'"
          file_pattern: index.html
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
