# .github/workflows/add-resource.yml
name: Add new resource

on:
  workflow_dispatch:
    inputs:
      category:
        description: "Category of the resource"
        required: true
        type: choice
        options:
          - book
          - blog
          - tweet
          - paper
          - personal
      title:
        description: "Title of the resource"
        required: true
        type: string
      url:
        description: "URL of the resource"
        required: true
        type: string

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update data file
        env:
          TITLE: ${{ github.event.inputs.title }}
          URL: ${{ github.event.inputs.url }}
          CATEGORY: ${{ github.event.inputs.category }}
        run: |
          # 1. Define the target file and map category to a placeholder marker
          FILE="index.html"
          case "$CATEGORY" in
            blog)     MARKER="let blogs = {" ;; # Match the opening brace
            tweet)    MARKER="let tweets = {" ;; # Match the opening brace
            book)     MARKER="let books = {" ;;  # Match the opening brace
            paper)    MARKER="let papers = {" ;; # Match the opening brace
            personal) MARKER="let personal = {" ;; # Match the opening brace
            *)        echo "Error: Unknown category '$CATEGORY'" && exit 1 ;;
          esac
          
          echo "Category: $CATEGORY"
          echo "Marker: $MARKER"

          # 2. Escape quotes in title and URL for safe insertion
          TITLE_ESC=$(echo "$TITLE" | sed 's/"/\\"/g')
          URL_ESC=$(echo "$URL" | sed 's/"/\\"/g')

          # 3. Prepare the new line to be inserted, WITH a trailing comma.
          # The indentation (4 spaces) is included for nice formatting.
          NEW_LINE="    \"${TITLE_ESC}\": \"${URL_ESC}\","

          # 4. Use sed to find the marker (the opening brace) and insert the new line AFTER it.
          # The 'a' command in sed appends text after the matched line.
          sed -i "/${MARKER}/a\\
${NEW_LINE}" "$FILE"

          echo "Successfully appended '$TITLE' to the '$CATEGORY' section in $FILE."

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(${{ github.event.inputs.category }}): Add '${{ github.event.inputs.title }}'"
          file_pattern: index.html
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
